[package]
name = "fifalog"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
axum = "0.5.16"
axum-extra = { version = "0.3.7", features = ["spa"] }
cookie = "0.16.0"
deadpool = "0.9.5"
deadpool-postgres = "0.10.2"
envy = "0.4.2"
rand = "0.8.5"
refinery = { version = "0.8.6", features = ["tokio-postgres"] }
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
tokio-postgres = { version = "0.7.7", features = ["with-serde_json-1"] }
tower = "0.4.13"
tower-cookies = { version = "0.7.0", features = ["signed"] }
tower-http = { version = "0.3.3", features = ["trace"] }
