[package]
name = "fifalog"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.59"
axum = "0.5.17"
axum-extra = { version = "0.3.7", features = ["spa"] }
cookie = "0.16.1"
deadpool = "0.9.5"
deadpool-postgres = "0.10.3"
envy = "0.4.2"
rand = "0.8.5"
refinery = { version = "0.8.7", features = ["tokio-postgres"] }
serde = { version = "1.0.151", features = ["derive"] }
time = { version = "0.3.17", features = ["formatting"] }
tokio = { version = "1.23.0", features = ["full"] }
tokio-postgres = { version = "0.7.7", features = ["with-serde_json-1", "with-time-0_3"] }
tower = "0.4.13"
tower-cookies = { version = "0.7.0", features = ["signed"] }
tower-http = { version = "0.3.5", features = ["trace"] }
