[package]
name = "fifalog"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
axum = "0.6.16"
cookie = "0.17.0"
deadpool = "0.9.5"
deadpool-postgres = "0.10.5"
envy = "0.4.2"
rand = "0.8.5"
refinery = { version = "0.8.7", features = ["tokio-postgres"] }
serde = { version = "1.0.160", features = ["derive"] }
time = { version = "0.3.20", features = ["formatting"] }
tokio = { version = "1.28.0", features = ["full"] }
tokio-postgres = { version = "0.7.8", features = ["with-serde_json-1", "with-time-0_3"] }
tower = "0.4.13"
tower-cookies = { version = "0.9.0", features = ["signed"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
