// Generated by sqltyper 1.0.1 from finishMatch.sql.
// Do not edit directly. Instead, edit finishMatch.sql and re-run sqltyper.

import { ClientBase, Pool } from 'pg'

export async function finishMatch(
  client: ClientBase | Pool,
  params: {
    homeScore: number | null
    awayScore: number | null
    finishedType: 'fullTime' | 'overTime' | 'penalties' | null
    homePenaltyGoals: number | null
    awayPenaltyGoals: number | null
    matchId: number
  }
): Promise<number> {
  const result = await client.query(
    `\
UPDATE match
SET
    finished_time = now(),
    home_score = $1,
    away_score = $2,
    finished_type = $3,
    home_penalty_goals = $4,
    away_penalty_goals = $5
WHERE
    id = $6
`,
    [
      params.homeScore,
      params.awayScore,
      params.finishedType,
      params.homePenaltyGoals,
      params.awayPenaltyGoals,
      params.matchId,
    ]
  )
  return result.rowCount
}
