// Generated by sqltyper 1.0.0 from leagues.sql.
// Do not edit directly. Instead, edit leagues.sql and re-run sqltyper.

import { ClientBase, Pool } from 'pg'

export async function leagues(
  client: ClientBase | Pool,
  params: { matchPairsToExclude: number }
): Promise<
  Array<{
    league_id: number
    league_name: string
    exclude_random_all: boolean
    team_id: number
    team_name: string
  }>
> {
  const result = await client.query(
    `\
WITH latest_matches AS (
        SELECT home_id, away_id
        FROM match
        ORDER BY finished_time DESC, id DESC
        LIMIT $1::integer * 2
    ), latest_teams (team_id) AS (
       SELECT home_id
       FROM latest_matches
       UNION
       SELECT away_id
       FROM latest_matches
    )
SELECT
  league.id as league_id,
  league.name as league_name,
  league.exclude_random_all as exclude_random_all,
  team.id as team_id,
  team.name as team_name
FROM league
JOIN team ON (team.league_id = league.id)
WHERE
  NOT team.disabled
  AND team.id NOT IN (SELECT team_id FROM latest_teams)
ORDER BY league.name, team.name
`,
    [params.matchPairsToExclude]
  )
  return result.rows
}
